# if File.exists?("~/.hashicorp.env")
#   tap "hashicorp/internal", "git@github.com:hashicorp/homebrew-internal.git"
#   tap "hashicorp/security", "git@github.com:hashicorp/homebrew-security.git"
#   brew "hashicorp/security/doormat-cli"
# end

tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "mutagen-io/mutagen"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"

brew "zsh"
brew "starship"

brew "achannarasappa/tap/ticker"
brew "ack"
brew "ansifilter"
brew "asdf"
brew "avr-gcc"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bash-git-prompt"
brew "bat"
brew "cloc"
brew "cmake"
brew "consul-template"
brew "coreutils"
brew "cowsay"
brew "ctags"
brew "curl"
brew "dbus"
brew "delve"
brew "enscript"
brew "exercism"
brew "findutils"
brew "fish"
brew "fortune"
brew "fpp"
brew "freetds"
brew "fzf"
brew "gawk"
brew "geckodriver"
brew "gh"
brew "git"
brew "git-gui"
brew "git-lfs"
brew "gnu-indent"
brew "gnu-sed", args: ["with-default-names"]
brew "gnu-tar"
brew "gnu-which"
brew "gnupg"
brew "go"
brew "golangci-lint"
brew "gpp"
brew "graphicsmagick"
brew "graphviz"
brew "grep"
brew "gtk+"
brew "hashicorp/tap/consul"
brew "hashicorp/tap/nomad"
brew "hashicorp/tap/packer"
brew "hashicorp/tap/sentinel"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/vault"
brew "hashicorp/tap/waypoint"
brew "heroku"
brew "hey"
brew "highlight"
brew "jq"
brew "librsvg"
brew "libxml2"
brew "lolcat"
brew "lua"
brew "lynx"
brew "markdown"
brew "mas"
brew "memcached"
brew "mkcert"
brew "moreutils"
brew "mosquitto"
brew "netcat"
brew "node"
brew "npm"
brew "openssh"
brew "p7zip"
brew "pandoc"
brew "python3"
brew "qmk/qmk/qmk"
brew "readline"
brew "reattach-to-user-namespace"
brew "redis"
brew "rename"
brew "shared-mime-info"
brew "sl"
brew "speedtest-cli"
brew "sqlite"
brew "ssh-copy-id"
brew "tfenv"
brew "tidy-html5"
brew "tmux"
brew "tmux-mem-cpu-load"
brew "tmuxp"
brew "todo-txt"
brew "tree"
brew "urlview"
brew "vim", args: ["override-system-vi"]
brew "watchman"
brew "webkit2png"
brew "wget", args: ["with-iri"]
brew "yarn"
brew "zopfli"

# cask "chromedriver"
# cask "postman"
# cask "sequel-pro"
# cask "sleek"
cask "1password"
cask "bambu-studio"
cask "caffeine"
cask "cleanmymac"
cask "corelocationcli"
cask "discord"
cask "disk-inventory-x"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-consolas-for-powerline"
cask "font-droid-sans-mono-for-powerline"
cask "font-droid-sans-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-for-powerline"
cask "font-open-sans"
cask "font-roboto"
cask "font-source-code-pro"
cask "gimp"
cask "google-chrome"
cask "google-drive"
cask "istat-menus"
cask "macdown"
cask "mtmr"
cask "ngrok"
cask "nordvpn"
cask "obsidian"
cask "pocket-casts"
cask "qmk-toolbox"
cask "quicklook-json"
cask "rowanj-gitx"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "todotxt"
cask "visual-studio-code"
cask "wkhtmltopdf"
cask "xscreensaver"
cask "zoom"

# Java
# tap "adoptopenjdk/openjdk"
# brew "gradle"
# brew "jenv"
# brew "maven"
# cask "adoptopenjdk"

# Clojure
# brew "leiningen"

mas "1Password for Safari", id: 1569813296
mas "Amazon Kindle", id: 302584613
mas "GarageBand", id: 682658836
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "SwiftoDo Desktop", id: 1143641091
mas "iMovie", id: 408981434
