tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
cask 'java'
brew 'git'
brew 'ack'
brew 'bash'
brew 'bash-completion'
brew 'bash-git-prompt'
brew 'carthage'
brew 'cloc'
brew 'cmake'
brew 'coreutils'
brew 'cowsay'
brew 'ctags'
brew 'curl'
brew 'exercism'
brew 'findutils'
brew 'fish'
brew 'fortune'
brew 'gcc'
brew 'git-lfs'
brew 'gnu-sed', args: ['with-default-names']
brew 'go'
brew 'gradle'
brew 'heroku'
brew 'highlight'
brew 'homebrew/boneyard/powerline'
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/openssh'
brew 'homebrew/python/numpy'
brew 'homebrew/science/r'
brew 'imagemagick', args: ['with-webp']
brew 'jq'
brew 'lua'
brew 'lynx'
brew 'mas'
brew 'memcached'
brew 'moreutils'
brew 'mosquitto'
brew 'node'
brew 'openssl'
brew 'p7zip'
brew 'pigz'
brew 'pv'
brew 'pygobject'
brew 'python'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'rename'
brew 'scala'
brew 'speedtest_cli'
brew 'sqlite'
brew 'ssh-copy-id'
brew 'tidy-html5'
brew 'tmux'
brew 'todo-txt'
brew 'tree'
brew 'vim', args: ['with-override-system-vi']
brew 'webkit2png'
brew 'wget', args: ['with-iri']
brew 'zopfli'
cask 'caffeine'
cask 'charles'
cask 'colloquy'
cask 'cyberduck'
cask 'dash'
cask 'disk-inventory-x'
cask 'docker'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'font-hack'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro'
cask 'get-lyrical'
cask 'gimp'
cask 'google-chrome'
cask 'growlnotify'
cask 'intellij-idea-ce'
cask 'istat-menus'
cask 'keycastr'
cask 'kitematic'
cask 'launchrocket'
cask 'macdown'
cask 'mojibar'
cask 'pgadmin4'
cask 'postgres'
cask 'roboto'
cask 'rowanj-gitx'
cask 'rstudio'
cask 'sequel-pro'
cask 'slack'
cask 'sublime-text'
cask 'virtualbox'
cask 'vlc'
mas 'Cocoa JSON Editor (1.2.5)', id: 442160773
mas 'Disk Care (1.5.1)', id: 913724705
mas 'HTTP Client (1.0.3)', id: 418138339
mas 'Keynote (6.6.2)', id: 409183694
mas 'Kindle (1.12.4)', id: 405399194
mas 'Numbers (3.6.2)', id: 409203825
mas 'OmniGraffle (6.6.1)', id: 711830901
mas 'Pages (5.6.2)', id: 409201541
mas 'Patterns (1.1.1)', id: 429449079
mas 'Soulver (2.6.0)', id: 413965349
mas 'The Unarchiver (3.11.1)', id: 425424353
mas 'Toolbox for Keynote (3.0.2)', id: 582635628
mas 'Tweetbot (2.4.4)', id: 557168941
mas 'Xcode (8.0)', id: 497799835
